Vagrant::Config.run do |config|

  config.vm.box = "ubuntu-12.04"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.define :web do | web_config |
    web_config.vm.customize ["modifyvm", :id, 
      "--name", "App Server (OOP 2013)",
      "--memory", "512",
      "--cpus", "2"
    ] 
    web_config.vm.host_name = "web.local"
    web_config.vm.network :hostonly, "33.33.13.12"
    
    web_config.vm.provision :chef_solo do |chef|
      chef.cookbooks_path = ["./cookbooks"]
      chef.run_list = [
        "recipe[myapp::web]"
      ]
      chef.json = {
        "java" => {
          "jdk_version" => "7"
        },
        "tomcat" => {
          "port" => 8080,
          "ssl_port" => 8443
        },
        "myapp" => {
          "web" => {
            "db_host" => "33.33.13.13"
          }
        }
      }
      chef.log_level = :info
    end
  end

  config.vm.define :db do | db_config |
    db_config.vm.customize ["modifyvm", :id, 
      "--name", "Database (OOP 2013)",
      "--memory", "512",
      "--cpus", "2" 
    ] 
    db_config.vm.host_name = "db.local"
    db_config.vm.network :hostonly, "33.33.13.13"

    db_config.vm.provision :chef_solo do |chef|
      chef.cookbooks_path = ["./cookbooks"]
      chef.run_list = [
        "recipe[myapp::db]"
      ]
      chef.json = {
        "postgresql" => {
          "password" => {
            "postgres" => "i_love_random_passwords_but_this_will_do"
          }
        }
      }
      chef.log_level = :info
    end
  end

end